import { phrase } from './text';

/**
 * Concept lexicon (SPEC §5.4). Patterns are regex sources in which a literal space matches any
 * whitespace; matching is case-insensitive unless an entry is marked `cs` (case-sensitive),
 * which is used for short abbreviations such as SOB or DM.
 */

type Entry = string | { cs: string };

const SIDE = '(?:left|right|l|r)';
const PRON = '(?:the |his |her |their |my )?';

export const LEXICON = {
  chest_pain: [
    '(?:central |left[- ]sided |left |retrosternal |substernal |crushing |tight )?chest (?:pain|tightness|pressure|heaviness|discomfort|ache)',
    'retrosternal pain',
    'substernal pain',
    'chest (?:feels |is )?tight',
    // "CP" is common clinic shorthand for chest pain (capitals only; rules v1.2.0).
    { cs: '(?:central |crushing |retrosternal )?CP' },
  ],
  chest_pain_pleuritic: [
    'pleuritic(?: chest)?(?: pain)?',
    'worse (?:on|with) (?:deep )?(?:breathing|inspiration|breathing in|inhalation)',
    'pain on (?:deep )?(?:breathing in|inspiration)',
    'hurts to breathe',
  ],
  radiation_arm_jaw: [
    `radiat(?:ing|es|ed|ion) (?:in)?to ${PRON}(?:both |${SIDE} )?(?:arm|arms|jaw|neck|shoulder|shoulders|back)`,
    `spreading to ${PRON}(?:${SIDE} )?(?:arm|jaw|neck|shoulder)`,
  ],
  diaphoresis: ['sweaty', 'sweating', 'diaphoretic', 'diaphoresis', 'clammy'],
  exertional: [
    'on exertion',
    'exertional',
    '(?:while|when|after) (?:climbing|walking|running|lifting|exercising|playing)',
    'during (?:exercise|exertion)',
  ],
  dyspnea: [
    'shortness of breath',
    'short of breath',
    { cs: 'SOB(?:OE)?' },
    'dyspno?ea',
    'dyspno?eic',
    'breathless(?:ness)?',
    'difficulty (?:in )?breathing',
    'breathing fast',
    'tachypno?e(?:a|ic)',
    'struggling to breathe',
    "(?:cannot|can not|can't) catch (?:his|her|their|my) breath",
  ],
  nausea_vomiting: [
    'nause(?:a|ated|ous)',
    'vomit(?:ing|ed|s)?',
    'emesis',
    'throwing up',
    'threw up',
  ],
  syncope: [
    'syncop(?:e|al)',
    'fainted',
    'passed out',
    'collapsed',
    'collapse',
    'loss of consciousness',
    { cs: 'LOC' },
  ],
  presyncope: [
    'felt faint',
    'feeling faint',
    'light[- ]?headed(?:ness)?',
    'dizz(?:y|iness)',
    'near[- ]syncope',
    'presyncop(?:e|al)',
  ],
  palpitations: ['palpitations?', 'racing heart', 'heart (?:is )?(?:racing|pounding)'],
  facial_droop: [
    `(?:${SIDE}(?:[- ]sided)? )?facial droop(?:ing)?`,
    'face (?:is )?drooping',
    'facial asymmetry',
    'drooping of (?:the )?(?:mouth|face)',
    `(?:${SIDE}(?:[- ]sided)? )?facial weakness`,
    '(?:mouth|face) droop(?:ing)?',
  ],
  unilateral_weakness: [
    'left[- ]sided weakness',
    'right[- ]sided weakness',
    '(?:left|right) (?:arm|leg|hand|side) weakness',
    `weakness (?:of|in) ${PRON}(?:left|right) (?:arm|leg|hand|side)`,
    `weakness on ${PRON}(?:left|right) side`,
    '(?:left|right) (?:arm|leg|hand) (?:is |feels )?weak',
    'hemipar(?:esis|etic)',
    'hemipleg(?:ia|ic)',
    'unilateral weakness',
  ],
  unilateral_numbness: [
    '(?:left|right)[- ]sided numbness',
    `numbness (?:of|in) ${PRON}(?:left|right) (?:arm|leg|hand|face|side)`,
    '(?:left|right) (?:arm|leg|hand|face) (?:numbness|is numb)',
  ],
  speech_disturbance: [
    'slurred speech',
    'speech (?:is |was )?slurred',
    'slurring(?: of speech| of words)?',
    'dysarthri(?:a|c)',
    'aphasi(?:a|c)',
    'dysphasi(?:a|c)',
    'difficulty (?:speaking|talking|finding words)',
    'word[- ]finding difficult(?:y|ies)',
    'garbled speech',
    'unable to speak',
  ],
  vision_loss_sudden: [
    'sudden (?:loss of vision|vision loss|visual loss|blindness)',
    'double vision',
    'diplopia',
    'visual field (?:loss|defect)',
    'loss of vision in one eye',
  ],
  ataxia: ['ataxi(?:a|c)', 'sudden (?:loss of balance|unsteadiness)'],
  sudden_onset: [
    'sudden(?:ly)?',
    'sudden[- ]onset',
    'abrupt(?:ly)?',
    'came on suddenly',
    'acute[- ]onset',
  ],
  headache: ['headaches?', 'head pain', 'cephalgia'],
  thunderclap: [
    'thunderclap(?: headache)?',
    'worst headache (?:of (?:my|her|his|their) life|ever)',
    'sudden(?:[- ]onset)? severe (?:[a-z]+ )?headache',
    'headache (?:that )?peak(?:ed|ing|s)? within (?:a |one |1 )?minutes?',
  ],
  neck_stiffness: [
    'neck stiffness',
    'stiff neck',
    'nuchal rigidity',
    'neck rigidity',
    'meningism(?:us)?',
  ],
  photophobia: [
    'photophobi(?:a|c)',
    'light hurts (?:his |her |their |my )?eyes',
    'sensitive to light',
  ],
  nonblanching_rash: [
    'non[- ]?blanching(?: rash| spots)?',
    'petechia(?:e|l)?(?: rash)?',
    'purpur(?:a|ic)(?: rash)?',
    "(?:rash|spots)[^.;\\n]{0,40}?(?:do|does|did)(?: not|n't) (?:fade|blanch)",
    'positive glass test',
    'glass test (?:is |was )?positive',
  ],
  confusion: [
    'confus(?:ed|ion)',
    'disorient(?:ed|ation)',
    'altered mental (?:status|state)',
    { cs: 'AMS' },
    'delirium',
    'delirious',
    'not making sense',
  ],
  drowsy: [
    'drows(?:y|iness)',
    'letharg(?:ic|y)',
    'hard to (?:wake|rouse)',
    'difficult to (?:wake|rouse)',
    'somnolent',
    'obtunded',
  ],
  unresponsive: ['unresponsive', 'unconscious', 'not responding', 'responds only to pain'],
  airway_swelling: [
    '(?:lip|lips|tongue|throat|face|facial)(?: and (?:lip|lips|tongue|throat|face))? swelling',
    `swelling of ${PRON}(?:lips?|tongue|throat|face)`,
    'swollen (?:lips?|tongue|face|throat)',
    'angio-?o?edema',
  ],
  throat_tightness: ['throat (?:feels |is )?(?:tight|closing)', 'throat tightness', 'tight throat'],
  stridor: ['stridor'],
  wheeze: ['wheez(?:e|es|ing|y)'],
  urticaria: ['hives', 'urticari(?:a|al)(?: rash)?'],
  allergen_exposure: [
    'after (?:eating|taking|ingesting|a (?:bee |wasp |insect )?sting|an injection)',
    '(?:bee|wasp|insect) sting',
    'stung by',
    'ate (?:peanuts?|nuts|shellfish|prawns|shrimp)',
    '(?:peanut|nut|shellfish|penicillin|latex) exposure',
    'exposure to (?:peanuts?|nuts|shellfish|penicillin|latex)',
  ],
  hematemesis: [
    'ha?ematemesis',
    'vomit(?:ing|ed) (?:up )?blood',
    'coffee[- ]grounds? (?:vomit|emesis|vomitus)',
    `blood in ${PRON}vomit`,
  ],
  melena: ['ma?elena', 'black (?:tarry )?stools?', 'tarry stools?'],
  rectal_bleeding: [
    'rectal bleed(?:ing)?',
    'bleeding per rectum',
    { cs: 'PR bleed(?:ing)?' },
    `blood in ${PRON}stools?`,
    'fresh (?:red )?blood per rectum',
    'bright red blood (?:per rectum|PR)',
  ],
  abdominal_pain: [
    '(?:(?:lower|upper|left|right|central|generali[sz]ed|severe|sharp|mild) )*(?:abdominal|abdo|stomach|belly|epigastric|pelvic|tummy|loin) pain',
    { cs: '(?:RUQ|RIF|LIF|LUQ|RLQ|LLQ) pain' },
    'abdominal tenderness',
    'pain in (?:the |his |her )?(?:abdomen|stomach|belly)',
  ],
  peritonism: [
    'rigid abdomen',
    'abdomen (?:is )?rigid',
    'board[- ]like (?:abdomen|rigidity)',
    'guarding',
    'rebound tenderness',
    'periton(?:ism|itic)',
  ],
  testicular_pain: [
    'testicular pain',
    'scrotal pain',
    'pain in (?:the |his |a |one )?(?:testicle|testis|scrotum)',
    '(?:left|right) testicle (?:pain|is painful)',
  ],
  vaginal_bleeding: [
    'vaginal bleed(?:ing)?',
    { cs: 'PV bleed(?:ing)?' },
    'bleeding per vagina',
    'spotting',
  ],
  shoulder_tip_pain: ['shoulder[- ]tip pain'],
  reduced_fetal_movements: [
    '(?:reduced|decreased) (?:fetal|foetal) movements?',
    'baby (?:is |has been )?moving (?:much |a lot )?less',
    '(?:fewer|less) (?:fetal |foetal |baby )?(?:movements?|kicks)',
    'not felt (?:the )?baby move',
    'no (?:fetal|foetal) movements?',
    { cs: 'RFM' },
  ],
  visual_disturbance: [
    'blurr?(?:ed|y) vision',
    'visual (?:disturbances?|changes?)',
    'flashing lights',
    'seeing spots',
  ],
  edema: [
    'o?edema',
    `swelling of ${PRON}(?:face|hands|feet|ankles)`,
    'swollen (?:ankles|feet|hands|legs)',
    'pedal o?edema',
  ],
  polydipsia_polyuria: [
    '(?:very|extremely|excessively) thirsty',
    'excessive thirst',
    'polydipsi(?:a|c)',
    'polyuri(?:a|c)',
    'passing (?:a lot of|lots of|large amounts of) urine',
    'urinating (?:a lot|frequently)',
  ],
  kussmaul: [
    'kussmaul(?: breathing| respirations?)?',
    'deep sighing breathing',
    'fruity breath',
    'ketotic breath',
  ],
  back_pain: [
    '(?:(?:low|lower|upper|mid|lumbar) )?back ?pain',
    'backache',
    { cs: 'LBP' },
    'lumbar pain',
  ],
  saddle_anesthesia: [
    'saddle (?:an(?:a)?esthesia|numbness|paraesthesia|paresthesia)',
    `numb(?:ness)? (?:around|in|of|over) ${PRON}(?:buttocks|perineum|perineal area|groin|genitals|inner thighs|saddle area)`,
  ],
  urinary_retention: [
    'urinary retention',
    'retention of urine',
    'difficulty (?:passing urine|urinating|voiding)',
    '(?:unable|inability) to (?:pass urine|urinate|void)',
    "can'?t pass urine",
  ],
  incontinence: [
    '(?:urinary|faecal|fecal|bowel|bladder|double) incontinence',
    '(?:urinary|faecal|fecal|bowel|bladder) (?:or|and) (?:urinary|faecal|fecal|bowel|bladder) incontinence',
    'incontinent(?: of (?:urine|faeces|feces|stool))?',
    'loss of (?:bladder|bowel) control',
  ],
  bilateral_leg_symptoms: [
    'bilateral leg (?:weakness|numbness|tingling|paraesthesia|paresthesia)',
    '(?:weakness|numbness|tingling|paraesthesia|paresthesia|pins and needles) (?:in|of|down) both legs',
    'both legs (?:are |feel )?(?:weak|numb)',
  ],
  suicidal: [
    'suicid(?:al|e)(?: ideation| thoughts| plan| attempt)?',
    '(?:thinking about|thoughts of|thought about|thinks about) (?:ending|taking) (?:his|her|their|my) (?:own )?life',
    '(?:thinking about|thoughts of) killing (?:him|her|them|my)sel(?:f|ves)',
    'wants? to die',
    'wish(?:es)? to die',
    '(?:looked up|searched for|researched) ways to (?:die|end|kill)',
    'self[- ]harm(?:ing)?',
    'intentional overdose',
  ],
  weight_loss: [
    '(?:unintentional|unexplained|unintended|significant) weight loss',
    'weight loss of (?:about |around |approximately |~)?\\d+(?:\\.\\d+)? ?kg',
    'lost (?:about |around |approximately )?\\d+(?:\\.\\d+)? ?kg',
  ],
  dysphagia: ['dysphagia', 'difficulty swallowing', 'trouble swallowing', 'food sticking'],
  night_sweats: ['night sweats'],
  hemoptysis: ['ha?emoptysis', 'coughing (?:up )?blood', 'blood[- ]stained sputum'],
  hematuria: ['ha?ematuria', `blood in ${PRON}urine`],
  postmenopausal_bleeding: ['post-?menopausal bleed(?:ing)?'],
  lump: ['lump', 'palpable mass'],
  fever_word: ['fever(?:ish|s)?', 'febrile', 'pyrexi(?:a|al)', 'high temperature', 'rigou?rs'],
  infection_source: [
    { cs: 'UTI' },
    'urinary tract infection',
    'dysuria',
    'burning (?:on|when|with) (?:urination|passing urine|peeing)',
    'pneumonia',
    'chest infection',
    'productive cough',
    'cough(?:ing)? (?:up |with )?(?:green |yellow )?(?:sputum|phlegm)',
    'cellulitis',
    'wound infection',
    'infected wound',
    'pyelonephritis',
  ],
  leg_swelling_unilateral: [
    '(?:left|right) (?:calf|leg) (?:swelling|swollen|is swollen|tender|tenderness|is tender)',
    'swollen (?:left|right) (?:calf|leg)',
    `swelling of ${PRON}(?:left|right) (?:calf|leg)`,
    'unilateral (?:leg|calf) swelling',
  ],
  recent_surgery_immobility: [
    '\\d+ (?:days?|weeks?) (?:after|post|following) (?:[a-z]+ )?(?:surgery|operation|op)',
    'after (?:[a-z]+ )?(?:surgery|operation)',
    'post-?op(?:erative)?(?:ly)?',
    'recent (?:surgery|operation|hospitali[sz]ation|admission)',
    'immobili[sz]ed',
    'bed-?bound',
    'long[- ]haul flight',
    'leg in (?:a )?cast',
  ],
  estrogen: [
    'combined (?:oral contraceptive )?pill',
    'the pill',
    'oral contraceptives?',
    { cs: 'C?OCP' },
    { cs: 'HRT' },
    'o?estrogen(?: therapy)?',
  ],
  prior_vte: [
    '(?:previous|prior|history of|hx of|past) (?:DVT|PE|VTE|blood clots?|pulmonary embol(?:ism|us)|deep vein thrombosis)',
  ],
  active_cancer: [
    'active cancer',
    'metastatic (?:cancer|disease)',
    'on chemo(?:therapy)?',
    'undergoing chemo(?:therapy)?',
  ],
  known_cad: [
    '(?:history of|hx of|previous|prior|known|old) (?:MI|myocardial infarction|heart attacks?|angina|CAD|IHD|coronary artery disease|ischa?emic heart disease)',
    'coronary stents?',
    { cs: 'CABG' },
    'angina',
    'ischa?emic heart disease',
    'coronary artery disease',
    { cs: 'IHD' },
    { cs: 'CAD' },
    '(?:had|has) (?:an? )?(?:MI|heart attack)',
    'myocardial infarction',
  ],
  diabetes: [
    'diabet(?:es|ic)',
    { cs: '(?:T1DM|T2DM|IDDM|NIDDM|DM)' },
    'type (?:1|2|one|two|I|II) diabetes',
    'insulin',
    'metformin',
  ],
  copd: [
    { cs: 'COPD' },
    'chronic obstructive',
    'emphysema',
    'chronic bronchitis',
    { cs: 'CO2 retainer' },
    'type 2 respiratory failure',
  ],
  grunting: ['grunting'],
  chest_indrawing: [
    'chest indrawing',
    '(?:chest|subcostal|intercostal|sternal) recession',
    'indrawing',
  ],
  cyanosis: ['cyanos(?:is|ed)', 'cyanotic', 'blue (?:lips|around the lips)'],
  floppy: ['floppy', 'hypotonic infant'],
  bulging_fontanelle: ['bulging fontanelle'],
  mottled: ['mottl(?:ed|ing)(?: skin)?', 'ashen'],
  weak_cry: ['(?:weak|high-pitched|continuous) cry'],
} satisfies Record<string, Entry[]>;

export type ConceptId = keyof typeof LEXICON;

export const CONCEPT_IDS = Object.keys(LEXICON) as ConceptId[];

export const COMPILED: Array<{ concept: ConceptId; re: RegExp }> = CONCEPT_IDS.flatMap((concept) =>
  (LEXICON[concept] as Entry[]).map((e) => ({
    concept,
    re: typeof e === 'string' ? phrase(e) : phrase(e.cs, true),
  })),
);

/** Human-readable labels used in generated rule reasoning. */
export const CONCEPT_LABELS: Record<ConceptId, string> = {
  chest_pain: 'Chest pain',
  chest_pain_pleuritic: 'Pleuritic pain',
  radiation_arm_jaw: 'Radiation to arm/jaw/neck',
  diaphoresis: 'Sweating',
  exertional: 'Exertional onset',
  dyspnea: 'Breathlessness',
  nausea_vomiting: 'Nausea/vomiting',
  syncope: 'Syncope',
  presyncope: 'Presyncope',
  palpitations: 'Palpitations',
  facial_droop: 'Facial droop',
  unilateral_weakness: 'Unilateral weakness',
  unilateral_numbness: 'Unilateral numbness',
  speech_disturbance: 'Speech disturbance',
  vision_loss_sudden: 'Sudden visual loss',
  ataxia: 'Ataxia',
  sudden_onset: 'Sudden onset',
  headache: 'Headache',
  thunderclap: 'Thunderclap features',
  neck_stiffness: 'Neck stiffness',
  photophobia: 'Photophobia',
  nonblanching_rash: 'Non-blanching rash',
  confusion: 'Confusion',
  drowsy: 'Drowsiness',
  unresponsive: 'Unresponsive',
  airway_swelling: 'Lip/tongue/throat swelling',
  throat_tightness: 'Throat tightness',
  stridor: 'Stridor',
  wheeze: 'Wheeze',
  urticaria: 'Urticaria',
  allergen_exposure: 'Possible allergen exposure',
  hematemesis: 'Haematemesis',
  melena: 'Melaena',
  rectal_bleeding: 'Rectal bleeding',
  abdominal_pain: 'Abdominal pain',
  peritonism: 'Peritonism',
  testicular_pain: 'Testicular pain',
  vaginal_bleeding: 'Vaginal bleeding',
  shoulder_tip_pain: 'Shoulder-tip pain',
  reduced_fetal_movements: 'Reduced fetal movements',
  visual_disturbance: 'Visual disturbance',
  edema: 'Oedema',
  polydipsia_polyuria: 'Thirst/polyuria',
  kussmaul: 'Kussmaul breathing',
  back_pain: 'Back pain',
  saddle_anesthesia: 'Saddle numbness',
  urinary_retention: 'Urinary retention',
  incontinence: 'Incontinence',
  bilateral_leg_symptoms: 'Bilateral leg symptoms',
  suicidal: 'Suicidal thoughts',
  weight_loss: 'Unintentional weight loss',
  dysphagia: 'Dysphagia',
  night_sweats: 'Night sweats',
  hemoptysis: 'Haemoptysis',
  hematuria: 'Haematuria',
  postmenopausal_bleeding: 'Postmenopausal bleeding',
  lump: 'Lump',
  fever_word: 'Fever',
  infection_source: 'Possible infection source',
  leg_swelling_unilateral: 'Unilateral leg swelling',
  recent_surgery_immobility: 'Recent surgery/immobility',
  estrogen: 'Oestrogen therapy',
  prior_vte: 'Previous VTE',
  active_cancer: 'Active cancer',
  known_cad: 'Known coronary disease',
  diabetes: 'Diabetes',
  copd: 'COPD',
  grunting: 'Grunting',
  chest_indrawing: 'Chest indrawing',
  cyanosis: 'Cyanosis',
  floppy: 'Floppy',
  bulging_fontanelle: 'Bulging fontanelle',
  mottled: 'Mottled/ashen skin',
  weak_cry: 'Weak/high-pitched cry',
};
